import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { joinPlayers } from "./join.js";
import { averageSkill, toBundlePlayer, type WorldBundlePlayer } from "./mapRatings.js";
import { parseCsv } from "./parse.js";

/**
 * `npm run build:world` — the manual FIR import step. Reads the scraper's
 * output CSVs from the gitignored `import-data/` dir, maps them onto the game
 * model, selects a roster, and writes the committed `data/world-bundle.json`.
 * The scraper itself never enters this repo; only this derived, open-source
 * artifact is shipped. See import/README.md.
 */

/** Roster cap per gender (Open decision 1). Keeps saves lean and draws
 * competitive; the floor of 63 is what a 64-player World Championships draw
 * needs from a single gender. */
const ROSTER_CAP_PER_GENDER = 150;
const MIN_PER_GENDER = 63;

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "../..");
const inputDir = resolve(pkgRoot, "import-data");
const outFile = resolve(pkgRoot, "data/world-bundle.json");

function readCsv(name: string): Record<string, string>[] {
  const path = resolve(inputDir, name);
  return parseCsv(readFileSync(path, "utf8"));
}

/**
 * Selects this gender's roster by systematic sampling across the *whole*
 * rated population's skill range, rather than the global top
 * `ROSTER_CAP_PER_GENDER`. Picking a pure top-N-by-skill roster (the old
 * behavior) produced a field with almost no skill spread at all: e.g. the
 * men's mapped skill only ranges ~200-735 (of 0-1000) end to end, but the
 * global top 150 all clustered in ~620-735 — division D ended up just as
 * strong as division A on average, since `divisionAssignments` had nothing
 * but elite players to split.
 *
 * Sorting the whole population strongest-first and taking every
 * `(pool.length - 1) / (cap - 1)`-th player instead spans that full range:
 * index 0 (the true strongest) is always included, so division A stays
 * genuinely elite, but the roster's weakest members are now genuinely weak
 * too, not just "the relatively weakest of the elite" — giving B/C/D real
 * variance once `divisionAssignments` bands them.
 */
function systematicSampleByGender(players: WorldBundlePlayer[], gender: "m" | "f"): WorldBundlePlayer[] {
  const pool = players
    .filter((p) => p.gender === gender)
    .sort((a, b) => averageSkill(b) - averageSkill(a) || a.playerId.localeCompare(b.playerId));
  if (pool.length < MIN_PER_GENDER) {
    throw new Error(
      `Only ${pool.length} ${gender} players after mapping — need at least ${MIN_PER_GENDER} for a 64-draw`,
    );
  }
  if (pool.length <= ROSTER_CAP_PER_GENDER) return pool;

  const roster: WorldBundlePlayer[] = [];
  for (let k = 0; k < ROSTER_CAP_PER_GENDER; k++) {
    const idx = Math.round((k * (pool.length - 1)) / (ROSTER_CAP_PER_GENDER - 1));
    roster.push(pool[idx]!);
  }
  return roster;
}

function main(): void {
  const playerRows = readCsv("players.csv");
  const joined = joinPlayers(
    [
      { gender: "m", rows: readCsv("ratings_men.csv") },
      { gender: "f", rows: readCsv("ratings_women.csv") },
    ],
    playerRows,
    readCsv("ranking_players.csv"),
  );

  const mapped: WorldBundlePlayer[] = [];
  const unmapped = new Set<string>();
  let noCountry = 0;
  for (const jp of joined) {
    // no country at all — missing data (mostly 1-3 game entries), skip quietly
    if (jp.countryIOC === "") {
      noCountry++;
      continue;
    }
    const bp = toBundlePlayer(jp);
    if (bp) mapped.push(bp);
    // a *present but unrecognised* code is a real mapping gap — fail loud below
    else unmapped.add(jp.countryIOC);
  }
  if (unmapped.size > 0) {
    throw new Error(`Unmapped IOC country codes (add to countryMap.ts): ${[...unmapped].sort().join(", ")}`);
  }
  if (noCountry > 0) console.log(`Skipped ${noCountry} players with no country code`);

  const roster = [...systematicSampleByGender(mapped, "m"), ...systematicSampleByGender(mapped, "f")].sort((a, b) =>
    a.playerId.localeCompare(b.playerId),
  );

  const men = roster.filter((p) => p.gender === "m").length;
  const women = roster.filter((p) => p.gender === "f").length;
  const rankedMen = roster.filter((p) => p.gender === "m" && p.firPoints !== null).length;
  const rankedWomen = roster.filter((p) => p.gender === "f" && p.firPoints !== null).length;
  console.log(
    `FIR points coverage: ${rankedMen}/${men} men, ${rankedWomen}/${women} women ` +
      `(the rest default to the lowest tournament division)`,
  );

  const bundle = {
    note: "Generated by npm run build:world from private FIR scraper output. Do not edit by hand.",
    counts: { men, women, total: roster.length },
    players: roster,
  };

  // 2-space, trailing newline — stable, diff-friendly (no timestamp)
  writeFileSync(outFile, `${JSON.stringify(bundle, null, 2)}\n`);
  console.log(`Wrote ${roster.length} players (${men} men, ${women} women) → ${outFile}`);
}

main();
