import type { Player } from "../model/player.js";
import type { Calendar } from "./date.js";

// v5: gender-separated tournament draws need a much deeper same-gender NPC
// pool (up to 63 opponents for a 64-player World Championships draw) than
// the world generator used to produce. GameState's shape is unchanged, but a
// save's `players` are generated once at career start and never
// regenerated — an old save's smaller, unfiltered-by-gender population would
// throw "not enough tier-1 players" the first time it tried to enter a
// tournament, so old saves are discarded rather than left to fail at runtime.
// v4 added the inbox; v3 added tournamentEntries.
// v6: PlayerAttributes gained `traits` (personality traits rolled at
// creation) — an old save's human has no traits array, so it's discarded
// rather than left with an undefined field the Me screen can't render.
export const SAVE_VERSION = 6;

/** A future tournament the human has committed to — see BALANCE.tournament.entryDeadlineWeeks. */
export interface TournamentEntry {
  weekIndex: number;
  tournamentId: string;
}

/** One frozen row in a monthly ranking digest — the standings as they were
 * when the mail was sent, so old digests keep reading correctly. */
export interface InboxRankingRow {
  rank: number;
  name: string;
  nationality: string;
  rating: number;
  isYou: boolean;
}

/**
 * A message in the human's inbox — the diegetic "living world" feed
 * (docs/07). Generated by InboxSystem, read-only over game state; carries its
 * own read flag and any actionable payload. Pre-rendered text keeps the save
 * self-contained and freezes point-in-time content (a ranking snapshot).
 */
export interface InboxMessage {
  id: string;
  /** week the message arrived */
  week: number;
  category: "welcome" | "invitation" | "ranking";
  from: string;
  subject: string;
  body: string;
  read: boolean;
  /** invitation only: the tournament's own week, for a Register/View action */
  tournamentWeek?: number;
  /** ranking digest only: the frozen monthly standings, top N */
  ranking?: InboxRankingRow[];
  /** ranking digest only: the human's own position that month */
  yourRank?: number;
}

/** Career-only state for the human player (AI players carry none of this). */
export interface Career {
  playerId: string;
  money: number; // EUR
  /** milestone titles earned, e.g. "champion" for a first tournament win */
  titles: string[];
  /** highest combined Glicko-2 rating ever reached, for personal-best tracking */
  bestRating: number;
  /** tournaments registered for but not yet played — consumed (removed) once
   * that week's tournament actually starts */
  tournamentEntries: TournamentEntry[];
  /** diegetic message feed, newest appended last — see InboxSystem */
  inbox: InboxMessage[];
}

export interface GameState {
  saveVersion: number;
  contentVersion: string;
  /** world seed — all RNG streams derive from this */
  seed: string;
  calendar: Calendar;
  players: Player[];
  career: Career;
}

export function getPlayer(state: GameState, id: string): Player {
  const player = state.players.find((p) => p.identity.id === id);
  if (!player) throw new Error(`Unknown player: ${id}`);
  return player;
}

export function humanPlayer(state: GameState): Player {
  return getPlayer(state, state.career.playerId);
}
