import type { ActivityType, ContentBundle, PlayerPlan, RealPlayerDef } from "../src/index.js";
import { SLOTS_PER_WEEK } from "../src/index.js";

/** A small deterministic real-player roster so world creation has a pool to
 * seed tier-1 NPCs from (mirrors the FIR world bundle). All null-firPoints
 * (unranked), so `divisionAssignments` (systems/division.ts) bands them by
 * skill alone, spread 100-900 across the pool. 68 per gender is enough that
 * even IWT.m's 4-band split (BALANCE.division.byTier) still clears 15 in
 * every band after the human takes one of that band's slots — the biggest
 * single-division field a test needs (the 16-draw monrad test, division "C"). */
const ROSTER_SIZE_PER_GENDER = 68;

function testRoster(): RealPlayerDef[] {
  const players: RealPlayerDef[] = [];
  for (const gender of ["m", "f"] as const) {
    for (let i = 0; i < ROSTER_SIZE_PER_GENDER; i++) {
      // even spread across the pool, so every division band gets real
      // representation once divisionAssignments bands unranked players by skill
      const base = Math.round(100 + (i * 800) / (ROSTER_SIZE_PER_GENDER - 1));
      const rating = { skill: base, rdSkill: 60 };
      players.push({
        playerId: `test-${gender}-${i}`,
        firstName: "Test",
        lastName: `${gender.toUpperCase()}${i}`,
        nationality: "SE",
        gender,
        birthYear: 1990 + (i % 15),
        ratings: { tt: rating, bd: rating, sq: rating, tn: rating },
        firPoints: null,
        endurance: 0.5,
        coreStrength: 0.5,
        clutch: 0.5,
        composure: 0.5,
      });
    }
  }
  return players;
}

/** Minimal content bundle so engine tests don't depend on @racketlon/content. */
export const testContent: ContentBundle = {
  version: "test",
  activities: {
    trainTT: { id: "trainTT", label: "Table tennis", short: "TT", sport: "tt", trainingBase: 6, fatigue: 7, money: -60, injuryLoad: 1.5 },
    trainBD: { id: "trainBD", label: "Badminton", short: "BD", sport: "bd", trainingBase: 6, fatigue: 7, money: -60, injuryLoad: 1.5 },
    trainSQ: { id: "trainSQ", label: "Squash", short: "SQ", sport: "sq", trainingBase: 6, fatigue: 7, money: -60, injuryLoad: 1.5 },
    trainTN: { id: "trainTN", label: "Tennis", short: "TN", sport: "tn", trainingBase: 6, fatigue: 7, money: -60, injuryLoad: 1.5 },
    gym: { id: "gym", label: "Gym", short: "Gym", fatigue: 6, money: -30, injuryLoad: 1.5 },
    cardio: { id: "cardio", label: "Cardio", short: "Run", fatigue: 5, money: 0, injuryLoad: 1.2 },
    rest: { id: "rest", label: "Rest", short: "—", fatigue: -6, money: 0, injuryLoad: 0 },
    work: { id: "work", label: "Work", short: "Job", fatigue: 4, money: 800, injuryLoad: 0 },
    social: { id: "social", label: "Social", short: "Soc", fatigue: -3, money: -100, injuryLoad: 0 },
    travel: { id: "travel", label: "Travel", short: "Travel", fatigue: 8, money: 0, injuryLoad: 0 },
  },
  names: {
    SE: { m: ["Test"], f: ["Test"], last: ["Player"] },
  },
  // SE is home (the default fallback human's nationality, used whenever
  // Game.newGame is called without a `character`) — NO is a foreign
  // destination for travel-cost tests.
  countries: {
    // A single fixed holiday on 2026-06-10 (a Wednesday) lets vacation tests
    // check the holiday exemption deterministically; 25-day base matches SE.
    SE: { name: "Sweden", lat: 60, lon: 15, costIndex: 1, president: "Test President", vacationDays: 25, holidays: { fixed: ["06-10"], easter: [] } },
    NO: { name: "Norway", lat: 60, lon: 5, costIndex: 1.5 },
  },
  firOfficials: {
    president: { role: "FIR President", name: "Test FIR President" },
    rankingsOfficer: { role: "FIR Rankings Officer", name: "Test Rankings Officer" },
  },
  // Three dated test tournaments landing on weekIndex 3, 7, 11 (Mondays
  // 2026-01-26 / 02-23 / 03-23) — stands in for what used to be a single
  // "every 4 weeks" recurring def, now that real events don't recur. All
  // domestic (country: SE = home) so they carry zero travel cost, keeping
  // entry-fee-only assertions elsewhere valid. A 4th, foreign tournament
  // (week 20, well past anything the default-count schedule tests slice)
  // exists solely for travel-cost tests.
  //
  // testRoster() never sets firPoints, so divisionAssignments bands every
  // NPC by skill alone (systems/division.ts), spreading them across every
  // band of a tier rather than dumping them all in the lowest one. The
  // default fallback human (a deliberate beginner, male, see world/factory.ts)
  // is still weak enough to land in the tier's lowest band regardless — men's
  // SAT (["A","B","C"]) -> "C", men's IWT (["A","B","C","D"]) -> "D" —
  // matching real content's default for a fresh career. humanEligibleDivisions (playing up — see
  // tournament/engine.ts) also needs every *tougher* division's row to exist
  // for these events, same as a real content author publishes every division
  // per event (enforced by packages/content/test/content.test.ts) — so each
  // event below also carries its tougher sibling rows.
  tournaments: {
    "monthly-open-1-m": {
      id: "monthly-open-1-m",
      eventId: "monthly-open-1",
      division: "B",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-01-26",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-1-f": {
      id: "monthly-open-1-f",
      eventId: "monthly-open-1",
      division: "B",
      gender: "f",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-01-26",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-1-a-m": {
      id: "monthly-open-1-a-m",
      eventId: "monthly-open-1",
      division: "A",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-01-26",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-1-a-f": {
      id: "monthly-open-1-a-f",
      eventId: "monthly-open-1",
      division: "A",
      gender: "f",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-01-26",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    // men-only: BALANCE.division.byTier.SAT.m has a 3rd ("C") band that
    // .f doesn't — mirrors real content's asymmetric SAT division counts
    "monthly-open-1-c-m": {
      id: "monthly-open-1-c-m",
      eventId: "monthly-open-1",
      division: "C",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-01-26",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-2-m": {
      id: "monthly-open-2-m",
      eventId: "monthly-open-2",
      division: "B",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-02-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-2-f": {
      id: "monthly-open-2-f",
      eventId: "monthly-open-2",
      division: "B",
      gender: "f",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-02-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-2-a-m": {
      id: "monthly-open-2-a-m",
      eventId: "monthly-open-2",
      division: "A",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-02-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-2-a-f": {
      id: "monthly-open-2-a-f",
      eventId: "monthly-open-2",
      division: "A",
      gender: "f",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-02-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    // men-only, same reason as monthly-open-1-c-m above
    "monthly-open-2-c-m": {
      id: "monthly-open-2-c-m",
      eventId: "monthly-open-2",
      division: "C",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-02-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-3-m": {
      id: "monthly-open-3-m",
      eventId: "monthly-open-3",
      division: "B",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-03-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-3-f": {
      id: "monthly-open-3-f",
      eventId: "monthly-open-3",
      division: "B",
      gender: "f",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-03-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-3-a-m": {
      id: "monthly-open-3-a-m",
      eventId: "monthly-open-3",
      division: "A",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-03-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "monthly-open-3-a-f": {
      id: "monthly-open-3-a-f",
      eventId: "monthly-open-3",
      division: "A",
      gender: "f",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-03-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    // men-only, same reason as monthly-open-1-c-m above
    "monthly-open-3-c-m": {
      id: "monthly-open-3-c-m",
      eventId: "monthly-open-3",
      division: "C",
      gender: "m",
      name: "Monthly Open",
      city: "Testville",
      country: "SE",
      lat: 60,
      lon: 15,
      tier: "SAT",
      date: "2026-03-23",
      nights: 1,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "intl-open-1-m": {
      id: "intl-open-1-m",
      eventId: "intl-open-1",
      division: "C",
      gender: "m",
      name: "International Open",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-05-25", // weekIndex 20
      nights: 2,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "intl-open-1-f": {
      id: "intl-open-1-f",
      eventId: "intl-open-1",
      division: "C",
      gender: "f",
      name: "International Open",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-05-25", // weekIndex 20
      nights: 2,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "intl-open-1-a-m": {
      id: "intl-open-1-a-m",
      eventId: "intl-open-1",
      division: "A",
      gender: "m",
      name: "International Open",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-05-25",
      nights: 2,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "intl-open-1-a-f": {
      id: "intl-open-1-a-f",
      eventId: "intl-open-1",
      division: "A",
      gender: "f",
      name: "International Open",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-05-25",
      nights: 2,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "intl-open-1-b-m": {
      id: "intl-open-1-b-m",
      eventId: "intl-open-1",
      division: "B",
      gender: "m",
      name: "International Open",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-05-25",
      nights: 2,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "intl-open-1-b-f": {
      id: "intl-open-1-b-f",
      eventId: "intl-open-1",
      division: "B",
      gender: "f",
      name: "International Open",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-05-25",
      nights: 2,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    // men-only: BALANCE.division.byTier.IWT.m has a 4th ("D") band that
    // .f doesn't — mirrors real content's asymmetric IWT division counts
    "intl-open-1-d-m": {
      id: "intl-open-1-d-m",
      eventId: "intl-open-1",
      division: "D",
      gender: "m",
      name: "International Open",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-05-25",
      nights: 2,
      entryFee: 300,
      fieldSize: 8,
      prizeByRoundsWon: [0, 200, 500, 1500],
    },
    "intl-open-2-m": {
      id: "intl-open-2-m",
      eventId: "intl-open-2",
      division: "C",
      gender: "m",
      name: "International Open Cup",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-08-03", // weekIndex 30
      nights: 3,
      entryFee: 300,
      fieldSize: 16,
      prizeByRoundsWon: [0, 150, 350, 800, 2000],
    },
    "intl-open-2-f": {
      id: "intl-open-2-f",
      eventId: "intl-open-2",
      division: "C",
      gender: "f",
      name: "International Open Cup",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-08-03", // weekIndex 30
      nights: 3,
      entryFee: 300,
      fieldSize: 16,
      prizeByRoundsWon: [0, 150, 350, 800, 2000],
    },
    "intl-open-2-a-m": {
      id: "intl-open-2-a-m",
      eventId: "intl-open-2",
      division: "A",
      gender: "m",
      name: "International Open Cup",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-08-03",
      nights: 3,
      entryFee: 300,
      fieldSize: 16,
      prizeByRoundsWon: [0, 150, 350, 800, 2000],
    },
    "intl-open-2-a-f": {
      id: "intl-open-2-a-f",
      eventId: "intl-open-2",
      division: "A",
      gender: "f",
      name: "International Open Cup",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-08-03",
      nights: 3,
      entryFee: 300,
      fieldSize: 16,
      prizeByRoundsWon: [0, 150, 350, 800, 2000],
    },
    "intl-open-2-b-m": {
      id: "intl-open-2-b-m",
      eventId: "intl-open-2",
      division: "B",
      gender: "m",
      name: "International Open Cup",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-08-03",
      nights: 3,
      entryFee: 300,
      fieldSize: 16,
      prizeByRoundsWon: [0, 150, 350, 800, 2000],
    },
    "intl-open-2-b-f": {
      id: "intl-open-2-b-f",
      eventId: "intl-open-2",
      division: "B",
      gender: "f",
      name: "International Open Cup",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-08-03",
      nights: 3,
      entryFee: 300,
      fieldSize: 16,
      prizeByRoundsWon: [0, 150, 350, 800, 2000],
    },
    // men-only, same reason as intl-open-1-d-m above
    "intl-open-2-d-m": {
      id: "intl-open-2-d-m",
      eventId: "intl-open-2",
      division: "D",
      gender: "m",
      name: "International Open Cup",
      city: "Foreignville",
      country: "NO",
      lat: 60,
      lon: 5,
      tier: "IWT",
      date: "2026-08-03",
      nights: 3,
      entryFee: 300,
      fieldSize: 16,
      prizeByRoundsWon: [0, 150, 350, 800, 2000],
    },
  },
  // a small pool covering every tone, plus one exclude pair, enough to
  // exercise rollTraits() without depending on @racketlon/content
  traits: {
    optimist: { id: "optimist", name: "Optimist", category: "mentality", tone: "positive", rarity: "common", description: "Test", excludes: ["pessimist"] },
    pessimist: { id: "pessimist", name: "Pessimist", category: "mentality", tone: "negative", rarity: "common", description: "Test", excludes: ["optimist"] },
    workhorse: { id: "workhorse", name: "Workhorse", category: "training", tone: "positive", rarity: "common", description: "Test" },
    lazy: { id: "lazy", name: "Lazy", category: "training", tone: "negative", rarity: "common", description: "Test" },
    creature_of_habit: { id: "creature_of_habit", name: "Creature of Habit", category: "training", tone: "neutral", rarity: "common", description: "Test" },
    aggressive: { id: "aggressive", name: "Aggressive", category: "competition", tone: "neutral", rarity: "uncommon", description: "Test" },
  },
  // A trimmed FIR points matrix (real Annex A values) for the two tiers these
  // test tournaments use — SAT only needs positions 1–8 (its one fieldSize-8
  // fixture), IWT needs 1–16 (its fieldSize-16 fixture too). See
  // packages/content/data/ranking-matrix.json.
  rankingMatrix: {
    SAT: {
      A: [633, 538, 475, 443, 380, 361, 342, 323],
      B: [253, 215, 190, 177, 152, 144, 137, 129],
      C: [101, 86, 76, 71, 61, 58, 55, 52],
      D: [41, 34, 30, 28, 24, 23, 22, 21],
    },
    IWT: {
      A: [1125, 956, 844, 788, 675, 641, 608, 574, 534, 478, 450, 422, 394, 366, 338, 309],
      B: [450, 383, 338, 315, 270, 257, 243, 230, 214, 191, 180, 169, 158, 146, 135, 124],
      C: [180, 153, 135, 126, 108, 103, 97, 92, 86, 77, 72, 68, 63, 59, 54, 50],
      D: [72, 61, 54, 50, 43, 41, 39, 37, 34, 31, 29, 27, 25, 23, 22, 20],
    },
  },
  players: testRoster(),
  injuries: {
    "ankle-sprain": {
      id: "ankle-sprain",
      label: "Ankle sprain",
      bodyPart: "ankle",
      kind: "injury",
      sportWeights: { sq: 3, bd: 3, tn: 1.5, tt: 0.3, gym: 0.3 },
    },
    "wrist-tendinitis": {
      id: "wrist-tendinitis",
      label: "Wrist tendinitis",
      bodyPart: "wrist",
      kind: "injury",
      sportWeights: { sq: 0.3, bd: 1, tn: 1, tt: 2.5, gym: 0.3 },
    },
    "back-spasm": {
      id: "back-spasm",
      label: "Back spasm",
      bodyPart: "back",
      kind: "injury",
      sportWeights: { sq: 1, bd: 1, tn: 1, tt: 0.5, gym: 2.5 },
    },
    "achilles-rupture": {
      id: "achilles-rupture",
      label: "Achilles rupture",
      bodyPart: "achilles",
      kind: "injury",
      sportWeights: { sq: 2, bd: 2, tn: 1, tt: 0.1, gym: 0.2 },
      severityWeights: [0, 0, 1],
      rare: true,
    },
  },
  illnesses: {
    flu: { id: "flu", label: "Flu", kind: "illness", severityWeights: [1, 3, 1] },
  },
};

/** Builds a 21-slot plan from activity counts, padding with rest. */
export function planWith(counts: Partial<Record<ActivityType, number>>): PlayerPlan {
  const slots: ActivityType[] = [];
  for (const [type, n] of Object.entries(counts) as Array<[ActivityType, number]>) {
    for (let i = 0; i < n; i++) slots.push(type);
  }
  if (slots.length > SLOTS_PER_WEEK) throw new Error("plan overflows the week");
  while (slots.length < SLOTS_PER_WEEK) slots.push("rest");
  return { slots };
}
